apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chatbot-jul30-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-jul30-1 
  name: chatbot-jul30-1
spec:
  ports:
  - name: app
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-jul30-1 
